name: "paper"
on:
  push:
    paths:
      - paper.md
      - paper.bib
  pull_request:
    paths:
      - paper.md
      - paper.bib

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build paper PDF
        uses: docker://pandoc/core:latest
        with:
          args: >-
            --standalone
            --filter pandoc-citeproc
            -o paper.pdf
            paper.md

      - name: Upload paper PDF
        uses: actions/upload-artifact@v3
        with:
          name: paper
          path: paper.pdf